FROM node
#WORKDIR /var/www/html/

#RUN npm install
# Для использования в продакшне
# RUN npm install --production

# Копирование файлов проекта
 

# Уведомление о порте, который будет прослушивать работающее приложение
EXPOSE 3000

# Запуск проекта
CMD ["node"]