FROM httpd:2.4
COPY config/httpd.conf /usr/local/apache2/conf/httpd.conf

RUN apt-get update -y

 
#USER root
#RUN chown -R www-data:www-data /var/www/html/
#RUN chmod -R 755 /var/www/html/storage
RUN apt-get install nano -y


 